services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    image: ks6088ts/azure-ai-services-solutions:backend-latest
    command: python main.py backend --port 8888 --debug
    ports:
      - 8888:8888
    volumes:
      - ./azure_ai_document_intelligence.env:/app/azure_ai_document_intelligence.env
      - ./azure_ai_vision.env:/app/azure_ai_vision.env
      - ./azure_event_grid.env:/app/azure_event_grid.env
      - ./azure_openai.env:/app/azure_openai.env
      - ./azure_storage_blob.env:/app/azure_storage_blob.env
      - ./azure_storage_queue.env:/app/azure_storage_queue.env
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    image: ks6088ts/azure-ai-services-solutions:frontend-latest
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0 -- frontend --solution-name sandbox --backend-url http://backend:8888 --debug
    ports:
      - 8501:8501
    volumes:
      - ./frontend.env:/app/frontend.env
    environment:
      - PYTHONUNBUFFERED=1
