services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ks6088ts/azure-ai-services-solutions:backend-latest
    command: python main.py backend --port 8888
    ports:
      - 8888:8888
    volumes:
      - ./backend:/app/
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    image: ks6088ts/azure-ai-services-solutions:frontend-latest
    command: streamlit run frontend/main.py
    ports:
      - 8501:8501
    volumes:
      - ./frontend/.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
